/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'apps',
    path: '/apps',
    component: 'layout.base$view.apps',
    meta: {
      title: 'apps',
      i18nKey: 'route.apps',
      icon: 'uim:apps',
      order: 2
    }
  },
  {
    name: 'code',
    path: '/code',
    component: 'layout.base$view.code',
    meta: {
      title: 'code',
      i18nKey: 'route.code',
      icon: 'material-symbols:credit-card-outline-sharp',
      order: 3
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'logs',
    path: '/logs',
    component: 'layout.base$view.logs',
    meta: {
      title: 'logs',
      i18nKey: 'route.logs',
      icon: 'mdi:alert-octagon',
      order: 5
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'solar:users-group-rounded-bold-duotone',
      order: 6
    }
  },
  {
    name: 'vars',
    path: '/vars',
    component: 'layout.base$view.vars',
    meta: {
      title: 'vars',
      i18nKey: 'route.vars',
      icon: 'mdi:application-variable-outline',
      order: 4
    }
  }
];